server {
    # Cloud Run은 구글이 HTTPS를 제공하므로 SSL 설정이 불필요
    # Cloud Run의 기본 포트 8080
    listen 8080;

    server_name nyamnyam.kr www.nyamnyam.kr;

    # Nginx가 React의 빌드된 정적 파일(index.html, .js, .css 등)을 찾을 루트 디렉토리
    # 기본 index 파일 설정: 요청이 폴더로 들어왔을 때 기본으로 제공할 파일
    index index.html;
    # 이 경로는 frontend.Dockerfile에서 파일을 복사한 위치
    root /usr/share/nginx/html;

    # ----------------------------------------------------
    # 프론트엔드 (React SPA) 서빙
    # ----------------------------------------------------
    # 모든 요청을 처리
    location / {
        # 이 설정이 SPA(Single Page Application)에서 매우 중요
        # Nginx가 요청된 URI($uri)를 찾지 못할 경우 (예: /about 경로), 
        # 404 오류 대신 React 앱의 기본 파일인 /index.html을 반환하여 
        # React Router가 경로 처리를 담당
        try_files $uri $uri/ /index.html; 
    }
    
    # ----------------------------------------------------
    # 👇 API 요청 백엔드 (NestJS) 프록시
    # ----------------------------------------------------
    # 브라우저에서 '/api/users'와 같은 요청이 오면,
    # Nginx가 이 요청을 Docker 네트워크 내부의 NestJS 컨테이너로 전달(API 요청을 백엔드 컨테이너로 프록시)
    location /api/ {
        # proxy_pass: Docker 네트워크 내부의 NestJS 컨테이너로 요청을 전달(요청을 전달할 목적지)
        proxy_pass https://siksa-backend-750045356743.asia-northeast3.run.app;
        
        proxy_set_header Host siksa-backend-750045356743.asia-northeast3.run.app;

        # 백엔드 서버가 클라이언트의 실제 IP와 호스트 정보를 알 수 있도록 헤더를 설정
        # proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # 💡 중요: NestJS에 요청이 HTTPS로 들어왔음을 알림
        #proxy_set_header X-Forwarded-Proto https;
    }
}