name: Deploy GCP VM
run-name: "[${{ github.ref_name }}] [${{ github.event.head_commit.message }}] [${{ github.actor }}]"

on:
  push:
    branches:
      - '**'

  # 💡 수동 실행(Manual Trigger) 옵션 추가 
  workflow_dispatch:
    inputs:
      commit_message:
        description: '임의 커밋 메시지'
        required: true
        default: 'Manual deploy' # 입력이 없을 경우 기본값

permissions:
  contents: read

jobs:
  # 1. pull_request 이벤트에서 레이블 검사만 하는 Job
  check_pr_label:
    runs-on: ubuntu-latest
    
    # pull_request 이벤트이고, 특정 레이블만 실행
    if: github.event_name == 'pull_request' 
       && (github.event.label.name == 'documentation' || github.event.label.name == 'dep')
    
    steps:
      - name: Label Check Passed
        run: echo "Label check passed for PR."

  deploy:
    # 이 작업이 실행될 가상 환경 정의 (GitHub Runner)
    runs-on: ubuntu-latest

    # check_pr_label Job에 의존합니다.
    # check_pr_label Job이 스킵되면 deploy Job은 실행됩니다.
    # (단, push 이벤트일 때만 해당 Job이 스킵되므로 의도대로 작동합니다.)
    needs: [check_pr_label]

    # 1) 이벤트가 'push' 이거나 (push 이벤트는 레이블과 무관하게 실행)
    # 2) 이벤트가 'pull_request'이고, 'check_pr_label' Job이 성공했을 때만 실행
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && success())
    
    steps:
      # Git 레포지토리의 코드를 Runner 환경으로 복제
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # 구글 클라우드 인증 단계 (추가 필요)
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }} # 서비스 계정 키 필요

      # gcloud SDK 설정
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      # Artifact Registry 인증 (Docker 로그인 대체)
      - name: 'Docker Auth'
        run: |-
          gcloud auth configure-docker asia-northeast3-docker.pkg.dev
      
      # Docker Hub 로그인
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Docker 빌드 환경 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
          
      # 프론트엔드 이미지 빌드 및 푸시 (frontend-app)
      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dockerfiles/frontend.Dockerfile 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/siksa-frontend-app:latest
          build-args: VITE_API_BASE_URL=${{ secrets.VITE_FRONTEND_API_BASE_URL }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # (SSH 대신) Cloud Run에 직접 배포하는 단계 추가
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: siksa-frontend # 서비스 이름
          image: ${{ secrets.DOCKERHUB_USERNAME }}/siksa-frontend-app:latest
          region: asia-northeast1 # 도쿄 리전
          flags: '--allow-unauthenticated' # 외부 접속 허용 (매우 중요!)